export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const NIGERIAN_CITIES = {
  Abia: ["Aba", "Arochukwu", "Bende", "Isuikwuato", "Ohafia", "Osisioma", "Umuahia"],
  Adamawa: ["Ganye", "Gombi", "Jimeta", "Michika", "Mubi", "Numan", "Song", "Yola"],
  "Akwa Ibom": ["Abak", "Eket", "Etiman", "Ikot Abasi", "Ikot Ekpene", "Oron", "Uyo"],
  Anambra: ["Agulu", "Awka", "Ekwulobia", "Ihiala", "Nnewi", "Ogidi", "Onitsha", "Ozubulu"],
  Bauchi: ["Azare", "Bauchi", "Dass", "Gamawa", "Jama'are", "Katagum", "Misau", "Ningi", "Tafawa Balewa"],
  Bayelsa: ["Brass", "Ekeremor", "Oporoma", "Sagbama", "Yenagoa"],
  Benue: ["Gboko", "Katsina-Ala", "Makurdi", "Oturkpo", "Otukpo", "Tarka", "Vandeikya", "Zaki Biam"],
  Borno: ["Biu", "Chibok", "Dikwa", "Gwoza", "Kukawa", "Maiduguri", "Ngala", "Nganzai"],
  "Cross River": ["Akamkpa", "Bekwarra", "Calabar", "Ikom", "Obubra", "Obudu", "Ogoja", "Yakurr"],
  Delta: ["Abraka", "Agbor", "Asaba", "Kwale", "Oleh", "Sapele", "Ughelli", "Warri"],
  Ebonyi: ["Abakaliki", "Afikpo", "Ezza", "Ishielu", "Ohaozara", "Onueke"],
  Edo: ["Auchi", "Benin City", "Ekpoma", "Irrua", "Sabongida-Ora", "Uromi"],
  Ekiti: ["Ado-Ekiti", "Efon-Alaaye", "Ikere-Ekiti", "Ikole-Ekiti", "Ise-Ekiti", "Oye-Ekiti"],
  Enugu: ["Agbani", "Awgu", "Enugu", "Nsukka", "Oji River", "Udi"],
  "FCT - Abuja": ["Abuja", "Asokoro", "Bwari", "Garki", "Gwagwalada", "Gwarinpa", "Kubwa", "Kuje", "Lugbe", "Maitama", "Wuse", "Zuba"],
  Gombe: ["Bajoga", "Billiri", "Dukku", "Gombe", "Kaltungo", "Nafada"],
  Imo: ["Mbaise", "Oguta", "Okigwe", "Orlu", "Oru East", "Owerri"],
  Jigawa: ["Birnin Kudu", "Dutse", "Gumel", "Hadejia", "Kazaure", "Ringim"],
  Kaduna: ["Kachia", "Kaduna", "Kafanchan", "Kagoro", "Saminaka", "Zaria"],
  Kano: ["Bichi", "Dambatta", "Gaya", "Kano", "Karaye", "Rano", "Wudil"],
  Katsina: ["Daura", "Dutsinma", "Funtua", "Kankia", "Katsina", "Mani"],
  Kebbi: ["Argungu", "Birnin Kebbi", "Kamba", "Yauri", "Yelwa", "Zuru"],
  Kogi: ["Ajaokuta", "Ankpa", "Idah", "Kabba", "Lokoja", "Okene"],
  Kwara: ["Ilorin", "Kaiama", "Lafiagi", "Offa", "Omu-Aran", "Patigi"],
  Lagos: ["Agege", "Ajah", "Alimosho", "Apapa", "Badagry", "Epe", "Festac", "Ikeja", "Ikorodu", "Isale-Eko", "Kosofe", "Lagos Island", "Lekki", "Mushin", "Ojo", "Surulere", "Victoria Island", "Yaba"],
  Nasarawa: ["Akwanga", "Doma", "Keffi", "Lafia", "Nasarawa", "Wamba"],
  Niger: ["Bida", "Kontagora", "Lapai", "Minna", "New Bussa", "Suleja"],
  Ogun: ["Abeokuta", "Ayetoro", "Ifo", "Ijebu-Ode", "Ilaro", "Ota", "Sagamu"],
  Ondo: ["Akure", "Ikare", "Ile-Oluji", "Okitipupa", "Ondo", "Ore", "Owo"],
  Osun: ["Ede", "Ikirun", "Ila-Orangun", "Ile-Ife", "Ilesa", "Iwo", "Osogbo"],
  Oyo: ["Ibadan", "Igboho", "Iseyin", "Ogbomosho", "Oyo", "Saki"],
  Plateau: ["Bokkos", "Jos", "Langtang", "Mangu", "Pankshin", "Shendam"],
  Rivers: ["Ahoada", "Bonny", "Degema", "Eleme", "Ikwerre", "Obio-Akpor", "Port Harcourt", "Rumuola"],
  Sokoto: ["Gwadabawa", "Isa", "Sokoto", "Tambuwal", "Wurno"],
  Taraba: ["Bali", "Jalingo", "Sardauna", "Takum", "Wukari", "Zing"],
  Yobe: ["Damaturu", "Gashua", "Geidam", "Nguru", "Potiskum"],
  Zamfara: ["Anka", "Gusau", "Kaura Namoda", "Talata Mafara", "Zurmi"],
};
