const tableData = [
  {
    id: 1,
    stationName: "Anele Oil & Gas",
    plan: "Plus",
    amount: "$199.00",
    paymentMethod: "Debit card",
    status: "Active",
    date: "Dec 31, 2025",
  },
  {
    id: 2,
    stationName: "Shell Downtown Hub",
    plan: "Plus",
    amount: "$199.00",
    paymentMethod: "Credit card",
    status: "Pending",
    date: "Dec 31, 2025",
  },
  {
    id: 3,
    stationName: "Shell Downtown Hub",
    plan: "Prime",
    amount: "$199.00",
    paymentMethod: "E. Transfers",
    status: "Pending",
    date: "Dec 31, 2025",
  },
  {
    id: 4,
    stationName: "Shell Downtown Hub",
    plan: "Basic",
    amount: "$199.00",
    paymentMethod: "Credit card",
    status: "Active",
    date: "Dec 31, 2025",
  },
  {
    id: 5,
    stationName: "Shell Downtown Hub",
    plan: "Basic",
    amount: "$199.00",
    paymentMethod: "Credit card",
    status: "Active",
    date: "Dec 31, 2025",
  },
  {
    id: 6,
    stationName: "Solvence",
    plan: "Basic",
    amount: "$199.00",
    paymentMethod: "Credit card",
    status: "Active",
    date: "Dec 31, 2025",
  },
  {
    id: 7,
    stationName: "NNPC Eliozu ",
    plan: "Basic",
    amount: "$199.00",
    paymentMethod: "Credit card",
    status: "Active",
    date: "Dec 31, 2025",
  },
  {
    id: 8,
    stationName: "Total Quartz",
    plan: "Basic",
    amount: "$199.00",
    paymentMethod: "Credit card",
    status: "Failed",
    date: "Dec 31, 2025",
  },
  {
    id: 9,
    stationName: "AP Rukpokwu",
    plan: "Basic",
    amount: "$199.00",
    paymentMethod: "Debit card",
    status: "Active",
    date: "Dec 31, 2025",
  },
  {
    id: 10,
    stationName: "A.A Rano",
    plan: "Basic",
    amount: "$199.00",
    paymentMethod: "E.Transfers",
    status: "Active",
    date: "Dec 31, 2025",
  },
  {
    id: 11,
    stationName: "NNPC Eliozu ",
    plan: "Basic",
    amount: "$199.00",
    paymentMethod: "Credit card",
    status: "Active",
    date: "Dec 31, 2025",
  },
  {
    id: 12,
    stationName: "Total Quartz",
    plan: "Basic",
    amount: "$199.00",
    paymentMethod: "Credit card",
    status: "Failed",
    date: "Dec 31, 2025",
  },
  {
    id: 13,
    stationName: "AP Rukpokwu",
    plan: "Basic",
    amount: "$199.00",
    paymentMethod: "Debit card",
    status: "Active",
    date: "Dec 31, 2025",
  },
  {
    id: 14,
    stationName: "A.A Rano",
    plan: "Basic",
    amount: "$199.00",
    paymentMethod: "E.Transfers",
    status: "Active",
    date: "Dec 31, 2025",
  },
];

export const tableHeaders = [
  { key: "stationName", label: "Station Name" },
  { key: "plan", label: "Plan" },
  { key: "amount", label: "Amount" },
  { key: "paymentMethod", label: "Payment Method" },
  { key: "status", label: "Status" },
  { key: "date", label: "Date" },
];

export default tableData;