import {
  ClipboardDocumentListIcon,
  DocumentTextIcon,
  BoltIcon,
  CreditCardIcon,
  ClockIcon,
  NoSymbolIcon,
  ExclamationTriangleIcon,
  CheckCircleIcon,
} from "@heroicons/react/24/outline";

export const auditLogHeaders = [
  { key: "eventType", label: "Event Type" },
  { key: "description", label: "Description" },
  { key: "stationUser", label: "Station/User" },
  { key: "status", label: "Status" },
  { key: "dateTime", label: "Date & Time" },
];

const auditLogData = [
  {
    id: 1,
    eventType: "Station registration",
    icon: ClipboardDocumentListIcon,
    description: "Shell Downtown Hub registered in Austin, TX",
    stationUser: "Shell Downtown Hub",
    status: "Info",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 2,
    eventType: "Updated subscription",
    icon: DocumentTextIcon,
    description: "Manual subscription plan adjustment",
    stationUser: "General Admin",
    status: "Info",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 3,
    eventType: "System alert",
    icon: BoltIcon,
    description: "High volume of failed payment attempts det...",
    stationUser: "System",
    status: "Critical",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 4,
    eventType: "Subscription payment",
    icon: CreditCardIcon,
    description: "Monthly subscription payment processed",
    stationUser: "BP Highway Express",
    status: "Success",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 5,
    eventType: "Subscription payment",
    icon: CreditCardIcon,
    description: "Monthly subscription payment processed",
    stationUser: "BP Highway Express",
    status: "Success",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 6,
    eventType: "Subscription expired",
    icon: ClockIcon,
    description: "Plus plan subscription expired – renewal requ...",
    stationUser: "BP Highway Express",
    status: "Warning",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 7,
    eventType: "Subscription expired",
    icon: ClockIcon,
    description: "Plus plan subscription expired – renewal requ...",
    stationUser: "BP Highway Express",
    status: "Warning",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 8,
    eventType: "Station suspended",
    icon: NoSymbolIcon,
    description: "Station suspended due to non-payment",
    stationUser: "BP Highway Express",
    status: "Critical",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 9,
    eventType: "Payment failed",
    icon: ExclamationTriangleIcon,
    description: "Payment method declined",
    stationUser: "BP Highway Express",
    status: "Critical",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 10,
    eventType: "Station reactivated",
    icon: CheckCircleIcon,
    description: "Station reactivated after payment verification",
    stationUser: "BP Highway Express",
    status: "Success",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 11,
    eventType: "Subscription expired",
    icon: ClockIcon,
    description: "Plus plan subscription expired – renewal requ...",
    stationUser: "BP Highway Express",
    status: "Warning",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 12,
    eventType: "Station suspended",
    icon: NoSymbolIcon,
    description: "Station suspended due to non-payment",
    stationUser: "BP Highway Express",
    status: "Critical",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 13,
    eventType: "Payment failed",
    icon: ExclamationTriangleIcon,
    description: "Payment method declined",
    stationUser: "BP Highway Express",
    status: "Critical",
    dateTime: "2025-06-19, 14:32",
  },
  {
    id: 14,
    eventType: "Station reactivated",
    icon: CheckCircleIcon,
    description: "Station reactivated after payment verification",
    stationUser: "BP Highway Express",
    status: "Success",
    dateTime: "2025-06-19, 14:32",
  },
];

export default auditLogData;