// You can also fetch this from an API later
const employeesData = [
  {
    id: 1,
    name: "Sam Melo",
    role: "Attendant",
    dutyStatus: true,
    shift: "One-Day (Morning) - 6am - 2pm",
    phone: "09030203425",
    email: "sammelo@gmail.com",
    earnings: "₦40,000",
    salesTarget: { current: 120000, total: 350000 },
    responsibilities: ["Fuel and diesel sales", "Pump operations", "Lubricant sales"],
  },
  {
    id: 2,
    name: "Grace Obi",
    role: "Cashier",
    dutyStatus: false,
    shift: "Afternoon - 2pm - 10pm",
    phone: "08123456789",
    email: "graceobi@gmail.com",
    earnings: "₦45,000",
    salesTarget: { current: 80000, total: 250000 },
    responsibilities: ["Cash handling", "Customer support", "Report keeping"],
  },
  {
    id: 3,
    name: "John Doe",
    role: "Manager",
    dutyStatus: true,
    shift: "Full Day - 6am - 6pm",
    phone: "08098765432",
    email: "johndoe@gmail.com",
    earnings: "₦120,000",
    salesTarget: { current: 200000, total: 500000 },
    responsibilities: ["Team supervision", "Sales monitoring", "Report submission"],
  },
  {
    id: 4,
    name: "John Doe",
    role: "Manager",
    dutyStatus: true,
    shift: "Full Day - 6am - 6pm",
    phone: "08098765432",
    email: "johndoe@gmail.com",
    earnings: "₦120,000",
    salesTarget: { current: 200000, total: 500000 },
    responsibilities: ["Team supervision", "Sales monitoring", "Report submission"],
  },
  {
    id: 5,
    name: "Maxwell Ekuase",
    role: "Manager",
    dutyStatus: true,
    shift: "Full Day - 6am - 6pm",
    phone: "08098765432",
    email: "johndoe@gmail.com",
    earnings: "₦120,000",
    salesTarget: { current: 200000, total: 500000 },
    responsibilities: ["Team supervision", "Sales monitoring", "Report submission"],
  },
  {
    id: 6,
    name: "Egwu Emmanuel",
    role: "Manager",
    dutyStatus: true,
    shift: "Full Day - 6am - 6pm",
    phone: "08098765432",
    email: "johndoe@gmail.com",
    earnings: "₦120,000",
    salesTarget: { current: 200000, total: 500000 },
    responsibilities: ["Team supervision", "Sales monitoring", "Report submission"],
  },
];

export default employeesData;
