// commissionsData.js

export const paymentData = [
  {
    staffName: "John Dave",
    role: "Attendant",
    sales: "123,000,000",
    commissionPercent: "2%",
    commissionAmount: "N5,000",
    bonus: "N3,000",
    totalEarnings: "N8,000",
    isPaid: true,   // ✅ true means Paid, false means Pay
  },
  {
    staffName: "John Dave",
    role: "Attendant",
    sales: "123,000,000",
    commissionPercent: "2%",
    commissionAmount: "N5,000",
    bonus: "N3,000",
    totalEarnings: "N8,000",
    isPaid: true,
  },
  {
    staffName: "John Dave",
    role: "Attendant",
    sales: "123,000,000",
    commissionPercent: "2%",
    commissionAmount: "N5,000",
    bonus: "N3,000",
    totalEarnings: "N8,000",
    isPaid: true,
  },
  {
    staffName: "John Dave",
    role: "Attendant",
    sales: "123,000,000",
    commissionPercent: "2%",
    commissionAmount: "N5,000",
    bonus: "N3,000",
    totalEarnings: "N8,000",
    isPaid: true,
  },
  {
    staffName: "John Dave",
    role: "Attendant",
    sales: "123,000,000",
    commissionPercent: "2%",
    commissionAmount: "N5,000",
    bonus: "N3,000",
    totalEarnings: "N8,000",
    isPaid: false,   // not yet paid
  },
  {
    staffName: "John Dave",
    role: "Attendant",
    sales: "123,000,000",
    commissionPercent: "2%",
    commissionAmount: "N5,000",
    bonus: "N3,000",
    totalEarnings: "N8,000",
    isPaid: true,
  },
  {
    staffName: "John Dave",
    role: "Attendant",
    sales: "123,000,000",
    commissionPercent: "2%",
    commissionAmount: "N5,000",
    bonus: "N3,000",
    totalEarnings: "N8,000",
    isPaid: false,
  },
  {
    staffName: "John Dave",
    role: "Attendant",
    sales: "123,000,000",
    commissionPercent: "2%",
    commissionAmount: "N5,000",
    bonus: "N3,000",
    totalEarnings: "N8,000",
    isPaid: false,
  },
  {
    staffName: "Odey Grace",
    role: "Cashier",
    sales: "123,000,000",
    commissionPercent: "3%",
    commissionAmount: "N5,000",
    bonus: "N3,000",
    totalEarnings: "N8,000",
    isPaid: false,
  },
  {
    staffName: "John Doe",
    role: "Accountant",
    sales: "123,000,000",
    commissionPercent: "2%",
    commissionAmount: "N5,000",
    bonus: "N3,000",
    totalEarnings: "N8,000",
    isPaid: false,
  },
  {
    staffName: "Maxwell Dave",
    role: "Supervisor",
    sales: "123,000,000",
    commissionPercent: "4%",
    commissionAmount: "N5,000",
    bonus: "N3,000",
    totalEarnings: "N8,000",
    isPaid: false,
  },
];

export const paymentColumns = [
  { header: "Staff name", accessor: "staffName" },
  { header: "Role", accessor: "role" },
  { header: "Sales", accessor: "sales" },
  { header: "Commission %", accessor: "commissionPercent" },
  { header: "Commission amount", accessor: "commissionAmount" },
  { header: "Bonus", accessor: "bonus" },
  { header: "Total earnings", accessor: "totalEarnings" },
  { header: "Action", accessor: "isPaid" }, // ✅ now tied to boolean
];
