export const columnsData = [
  "Date",
  "EXP_ID",
  "Category",
  "Description",
  "Amount",
  "Submitted by",
  "Status",
];

export const rowsData = [
  [
    "04/17/23",
    "#exp1232",
    "Administrative",
    "Renovation of station structure",
    "₦120,000,000",
    "John Dave - Manager",
    "Approved ✓",
  ],
  [
    "04/17/23",
    "#exp1232",
    "Maintenance & Repair",
    "Renovation of station structure",
    "₦120,000,000",
    "John Dave - Manager",
    "Approved ✓",
  ],
  [
    "04/17/23",
    "#exp1232",
    "Maintenance & Repair",
    "Renovation of station structure",
    "₦120,000,000",
    "John Dave - Manager",
    "Approved ✓",
  ],
  [
    "04/17/23",
    "#exp1233",
    "Equipment Purchase",
    "New fuel pump installation",
    "₦85,000,000",
    "Sarah Wilson - Supervisor",
    "Pending",
  ],
  [
    "04/18/23",
    "#exp1234",
    "Maintenance & Repair",
    "Generator maintenance",
    "₦25,000,000",
    "Mike Johnson - Technician",
    "Rejected",
  ],
  [
    "04/19/23",
    "#exp1235",
    "Utilities",
    "Monthly electricity bill",
    "₦15,000,000",
    "Admin Department",
    "Approved ✓",
  ],
];
