import React, { useEffect } from 'react';
import TableWithoutBorder from '@/components/TableWithoutBorder';
import { useExpenseStore } from '@/store/expenseStore';
import { tableHeaders } from './expenseMgtData';

const ExpenseMgtPage = () => {
  const { expenses, fetchExpenses, loading } = useExpenseStore();

  useEffect(() => {
    // Fetch expenses when component mounts
    fetchExpenses();
  }, [fetchExpenses]);

  // Refetch when window gains focus (to get updates from other pages)
  useEffect(() => {
    const handleFocus = () => {
      fetchExpenses();
    };
    
    window.addEventListener('focus', handleFocus);
    return () => window.removeEventListener('focus', handleFocus);
  }, [fetchExpenses]);

  // Sort expenses by date (newest first - top to bottom)
  const sortedExpenses = [...expenses].sort((a, b) => {
    const dateA = new Date(a.createdAt);
    const dateB = new Date(b.createdAt);
    return dateB - dateA; // Descending order (newest first)
  });

  // Transform expenses data into table rows format (array of arrays)
  const tableRows = sortedExpenses.map((expense) => {
    // Handle submittedBy - can be string or object
    let submittedBy = 'N/A';
    if (typeof expense.submittedBy === 'string') {
      submittedBy = expense.submittedBy;
    } else if (expense.submittedBy && typeof expense.submittedBy === 'object') {
      submittedBy = `${expense.submittedBy.firstName} ${expense.submittedBy.lastName} - ${expense.submittedBy.role || "Staff"}`;
    }

    return [
      // Date - already formatted by backend
      expense.date || 'N/A',
      // EXP ID - already generated by backend
      expense.expId || 'N/A',
      // Category
      expense.category,
      // Description
      expense.description,
      // Amount
      `₦${parseFloat(expense.amount).toLocaleString()}`,
      // Submitted by
      submittedBy,
      // Status
      expense.status === 'Approved' ? 'Approved ✓' : 
      expense.status === 'Rejected' ? 'Rejected ✗' : 
      'Pending ⏳'
    ];
  });

  return (
    <div className='bg-white p-5 rounded-2xl'>
      <div className='mb-[1.5rem]'>
        <h1 className='text-[1.375rem] font-semibold leading-[134%] text-neutral-800'>
          Expense Management
        </h1>
        <p className='text-[1rem] text-neutral-800 leading-[150%]'>
          Track, add and export expense reports
        </p>
      </div>

      {loading.expenses ? (
        <div className="flex items-center justify-center py-10">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
        </div>
      ) : expenses.length === 0 ? (
        <div className="text-center py-10 text-gray-500">
          No expenses found. Add your first expense!
        </div>
      ) : (
        <TableWithoutBorder columns={tableHeaders} data={tableRows} />
      )}
    </div>
  );
};

export default ExpenseMgtPage;