const activityLogsTable = {
  header: [
    "Date",
    "User",
    "Role",
    "Action",
    "Description",
    "IP address",
    "Status",
  ],
  body: [
    [
      "04/17/23, 8:25 PM",
      "John Melo",
      "Attendant",
      "Failed login",
      "Error logging in due to network",
      "IP-1343-34546",
      "Failed",
    ],
    [
      "04/17/23, 8:25 PM",
      "John Melo",
      "Supervisor",
      "Shift Approved",
      "Reconciled shift approved by supervisor",
      "IP-1343-34546",
      "Success",
    ],
    [
      "04/17/23, 8:25 PM",
      "John Melo",
      "Attendant",
      "Failed login",
      "Error logging in due to network",
      "IP-1343-34546",
      "Failed",
    ],
    [
      "04/17/23, 8:25 PM",
      "System",
      "System",
      "Automatic backup",
      "System backup complete",
      "IP-1343-34546",
      "Success",
    ],
    [
      "04/17/23, 8:25 PM",
      "John Melo",
      "Attendant",
      "Shift closed",
      "Morning shift closed",
      "IP-1343-34546",
      "Success",
    ],
    [
      "04/17/23, 8:25 PM",
      "John Melo",
      "Attendant",
      "Shift closed",
      "Morning shift closed",
      "IP-1343-34546",
      "Success",
    ],
    [
      "04/17/23, 8:25 PM",
      "John Melo",
      "Attendant",
      "Failed login",
      "Evening shift closed",
      "IP-1343-34546",
      "Success",
    ],
    [
      "04/17/23, 8:25 PM",
      "John Melo",
      "Attendant",
      "Failed login",
      "Error logging in due to network",
      "IP-1343-34546",
      "Success",
    ],
    [
      "04/17/23, 8:25 PM",
      "John Melo",
      "Attendant",
      "Failed login",
      "Error logging in due to network",
      "IP-1343-34546",
      "Success",
    ],
    [
      "04/17/23, 8:25 PM",
      "John Melo",
      "Attendant",
      "Failed login",
      "Error logging in due to network",
      "IP-1343-34546",
      "Failed",
    ],
    [
      "04/17/23, 8:25 PM",
      "John Melo",
      "Attendant",
      "Failed login",
      "Error logging in due to network",
      "IP-1343-34546",
      "Failed",
    ],
  ],
};

export default activityLogsTable;
