// export const stationsTableData = {
//   headers: [
//     { key: "id", label: "ID" },
//     { key: "stationName", label: "Station Name" },
//     { key: "owner", label: "Owner Name" },
//     { key: "plan", label: "Plan" },
//     { key: "expiryDate", label: "Expiry Date" },
//     { key: "status", label: "Status" },
//     { key: "action", label: "Action" },
//   ],

//   rows: [
//     {
//       id: "ST-001",
//       stationName: "Shell Downtown Hub",
//       owner: "Austin, TX",
//       plan: "Prime",
//       expiryDate: "Dec 31, 2025",
//       status: "Active",
//       action: "...",
//     },
//     {
//       id: "ST-002",
//       stationName: "Alison Oil & Gas",
//       owner: "Lagos, Nigeria",
//       plan: "Plus",
//       expiryDate: "Dec 31, 2025",
//       status: "Active",
//       action: "...",
//     },
//     {
//       id: "ST-003",
//       stationName: "Chevron North Station",
//       owner: "Houston, TX",
//       plan: "Basic",
//       expiryDate: "Dec 31, 2025",
//       status: "Maintenance",
//       action: "...",
//     },
//     {
//       id: "ST-004",
//       stationName: "Exxon Mobile East",
//       owner: "Abuja, Nigeria",
//       plan: "Plus",
//       expiryDate: "Dec 31, 2025",
//       status: "Active",
//       action: "...",
//     },
//     {
//       id: "ST-005",
//       stationName: "NNPC Oil",
//       owner: "Abuja, Nigeria",
//       plan: "Basic",
//       expiryDate: "Dec 31, 2025",
//       status: "Suspended",
//       action: "...",
//     },
//   ],
// };

export const stationsTableData = {
  headers: [
    { key: "id", label: "ID" },
    { key: "stationName", label: "Station Name" },
    { key: "owner", label: "Owner Name" },
    { key: "plan", label: "Plan" },
    { key: "expiryDate", label: "Expiry Date" },
    { key: "status", label: "Status" },
    { key: "action", label: "Action" },
  ],

  rows: [
    {
      id: "ST-001",
      stationName: "Shell Downtown Hub",
      owner: "Austin, TX",
      plan: "Prime",
      expiryDate: "Dec 31, 2025",
      status: "Active",
      action: "more",
    },
    {
      id: "ST-002",
      stationName: "Alison Oil & Gas",
      owner: "Lagos, Nigeria",
      plan: "Plus",
      expiryDate: "Dec 31, 2025",
      status: "Active",
      action: "more",
    },
    {
      id: "ST-003",
      stationName: "Chevron North Station",
      owner: "Houston, TX",
      plan: "Basic",
      expiryDate: "Dec 31, 2025",
      status: "Maintenance",
      action: "more",
    },
    {
      id: "ST-004",
      stationName: "Chevron North Station",
      owner: "Houston, TX",
      plan: "Basic",
      expiryDate: "Dec 31, 2025",
      status: "Maintenance",
      action: "more",
    },
    {
      id: "ST-005",
      stationName: "Chevron North Station",
      owner: "Houston, TX",
      plan: "Basic",
      expiryDate: "Dec 31, 2025",
      status: "Maintenance",
      action: "more",
    },
    {
      id: "ST-006",
      stationName: "Chevron North Station",
      owner: "Houston, TX",
      plan: "Basic",
      expiryDate: "Dec 31, 2025",
      status: "Maintenance",
      action: "more",
    },
    {
      id: "ST-007",
      stationName: "Chevron North Station",
      owner: "Houston, TX",
      plan: "Basic",
      expiryDate: "Dec 31, 2025",
      status: "Suspended",
      action: "more",
    },
    {
      id: "ST-008",
      stationName: "Chevron North Station",
      owner: "Houston, TX",
      plan: "Basic",
      expiryDate: "Dec 31, 2025",
      status: "Maintenance",
      action: "more",
    },
    {
      id: "ST-009",
      stationName: "Chevron North Station",
      owner: "Houston, TX",
      plan: "Basic",
      expiryDate: "Dec 31, 2025",
      status: "Suspended",
      action: "more",
    },
    {
      id: "ST-010",
      stationName: "Chevron North Station",
      owner: "Houston, TX",
      plan: "Basic",
      expiryDate: "Dec 31, 2025",
      status: "Suspended",
      action: "more",
    },
  ],
};

